App\Entity\Location:
  properties:
    latitude:
      - Range:
          min: -90
          max: 90
    longitude:
      - Range:
          min: -180
          max: 180
    city:
      - Length:
          min: 2
          max: 50
    country:
      - Length:
          min: 2
          max: 50

App\Entity\Measurement:
  properties:
    celsius:
      - Range:
          min: -100
          max: 100