#index:
#    path: /
#    controller: App\Controller\DefaultController::index

weather_in_city:
  path: /weather/{city}
  controller: App\Controller\WeatherController:cityAction
  requirements:
    city: \d+

weather:
  path: /weather/{country}/{city}
  controller: App\Controller\WeatherController:measurementAction

app_location:
  resource: 'routes/app_location.yaml'
  prefix: 'location'
  name_prefix: 'app_location_'

app_measurement:
  resource: 'routes/app_measurement.yaml'
  prefix: 'measurement'
  name_prefix: 'app_measurement_'